### PR TITLE
README Formatting

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Update Tags**

  - Split `arduino-library` ➞ `arduino` , `library`
  
  - Add `analog` , `digital` , `converter`

  <br>

- **Update Description**

  `Arduino Library for MPC3x6x Analog 🠖 Digital Converter.`

  <br>

  <br>

- ***[Disable Unused Widgets][Widgets]***:

  - `Releases`

  <br>

- ***[Disable Unused Tabs][Tabs]***:

  - `Wiki`

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Added license , status badge

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Arduino_MCP3x6x_Library

### CODE REVIEW

**Comment by nerdyscout** [comment]
thank you for your contribution. I am perfectly fine with the most of it. Just for the moment, as there are major bugs in the code, I would prefer to point this out in the readme so nobody will be surprised by this.

**Comment by ElectronicsArchiver** [comment]
Thats why I added the status-unstable badge~

**Comment by ElectronicsArchiver** [comment]
@nerdyscout Could you please follow up with this~

**Comment by ElectronicsArchiver** [comment]
wow.

**Pull request closed without merging**
